# src/blogRewriter/config/tasks.yaml
rewrite_blog_task:
  description: >
    Du wirst einen Blogbeitrag erhalten mit {word_count} Wörtern.
    Deine Aufgabe ist es, den folgenden Blogbeitrag zu rezyklieren und dabei einen neuen Text mit exakt einer Länge von {allowed_word_count} bis {word_count} Wörtern zu erstellen.
    Implementiere SEO anhand der Knowledge Source: json_seo
    Blogbeitrag: {content}
  expected_output: >
    Neu formulierter Blogbeitrag
  agent: blog_rewriter

create_linkedin_post_task:
  description: >
    Erstelle einen LinkedIn Post basierend auf folgendem Blogbeitrag:
    {content}

    Beachte dabei:
    - Implementiere SEO anhand der Knowledge Source: json_seo
    - Maximale Länge: 3000 Zeichen
    - Nutze 3-5 relevante Hashtags
    - Füge passende Emojis ein
    - Baue einen Call-to-Action ein
    - Formatiere den Text mit Absätzen für bessere Lesbarkeit 
  expected_output: >
    LinkedIn Post im korrekten Format mit Hashtags und Call-to-Action
  agent: linkedin_post_creator

create_whitepaper_task:
  description: >
    Analysiere den bestehenden Blog: {content}
    Erstelle daraus ein White Paper mit folgende Anforderungen:
      - Implementiere SEO anhand der Knowledge Source: json_seo
      - Eine sachliche und tiefgehende Auseinandersetzung mit dem Thema.
      - Darstellung eines spezifischen Problems und Lösungsansätzen, die den Mehrwert des Unternehmens herausstellen.
      - Klare Strukturierung in Abschnitte wie Einleitung, Hintergrund, Problemstellung, Lösungsansätze und Fazit.
      - Integration von Rechercheergebnissen, Praxisbeispielen und Statistiken.
      - Professionelle Positionierung des Unternehmens als vertrauenswürdiger Experte.
  expected_output: >
    Ein umfassendes White Paper
  agent: whitepaper_creator